export const VOCABULARY = [
  { word: "Resilient", definition: "Able to recover quickly from difficulties.", example: "Despite the harsh winter, the resilient plants bloomed again in spring." },
  { word: "Eloquent", definition: "Expressive and persuasive in speaking or writing.", example: "Her eloquent speech moved the entire audience to tears." },
  { word: "Curious", definition: "Eager to know or learn something.", example: "The curious child asked endless questions about the stars." },
  { word: "Venture", definition: "A risky or daring journey or undertaking.", example: "They decided to venture into the dark, unexplored cave." },
  { word: "Adapt", definition: "To adjust to new conditions.", example: "Chameleons can adapt their skin color to match their surroundings." },
  { word: "Insight", definition: "A deep understanding of a person or thing.", example: "The documentary provided valuable insight into marine biology." },
  { word: "Harmonious", definition: "Forming a pleasing or consistent whole.", example: "The choir's harmonious voices echoed beautifully through the hall." },
  { word: "Precise", definition: "Marked by exactness and accuracy of expression.", example: "The surgeon required a precise scalpel to perform the operation." },
  { word: "Subtle", definition: "So delicate or precise as to be difficult to analyze or describe.", example: "There was a subtle hint of cinnamon in the coffee." },
  { word: "Genuine", definition: "Real, sincere, and authentic.", example: "His genuine apology was accepted by everyone." },
  { word: "Fragile", definition: "Easily broken or damaged.", example: "Please handle this antique vase carefully; it is very fragile." },
  { word: "Emerge", definition: "To come into view or become known.", example: "The butterfly began to emerge from its cocoon." },
  { word: "Weary", definition: "Feeling very tired from work or effort.", example: "The weary traveler finally found a place to rest." },
  { word: "Mellow", definition: "Soft, smooth, and pleasant in tone or flavor.", example: "We relaxed to the mellow sounds of jazz." },
  { word: "Origin", definition: "The beginning or source of something.", example: "Scientists are still studying the origin of the universe." },
  { word: "Serene", definition: "Calm, peaceful, and untroubled.", example: "The lake looked absolutely serene under the moonlight." },
  { word: "Thrive", definition: "To grow, develop, or be successful.", example: "Succulents thrive in dry, desert climates." },
  { word: "Luminous", definition: "Emitting or reflecting light; bright.", example: "The luminous dial of the clock was visible in the dark." },
  { word: "Ponder", definition: "To think carefully about something.", example: "She took a moment to ponder the meaning of the poem." },
  { word: "Swift", definition: "Moving or capable of moving at high speed.", example: "The swift cheetah easily caught its prey." },
  { word: "Nimble", definition: "Quick and light in movement or action.", example: "The nimble gymnast executed a flawless backflip." },
  { word: "Robust", definition: "Strong and healthy; vigorous.", example: "A robust immune system helps fight off colds." },
  { word: "Classic", definition: "Judged over a period of time to be of the highest quality.", example: "That vintage car is considered a timeless classic." },
  { word: "Ambitious", definition: "Having a strong desire to achieve something.", example: "The ambitious entrepreneur started three successful companies." },
  { word: "Brisk", definition: "Quick and energetic in movement or action.", example: "We took a brisk walk through the park to warm up." },
  { word: "Loyal", definition: "Showing firm and constant support.", example: "Dogs are known for being incredibly loyal companions." },
  { word: "Tranquil", definition: "Free from disturbance; calm.", example: "The yoga studio offered a tranquil environment for meditation." },
  
  // Advanced / Expressive
  { word: "Ephemeral", definition: "Lasting for a very short time.", example: "The beauty of a sunset is ephemeral, fading into darkness." },
  { word: "Ubiquitous", definition: "Present, appearing, or found everywhere.", example: "Smartphones have become ubiquitous in modern society." },
  { word: "Tenacious", definition: "Tending to keep a firm hold of something; clinging or adhering closely.", example: "His tenacious grip on the rope saved him from falling." },
  { word: "Pragmatic", definition: "Dealing with things sensibly and realistically.", example: "We need a pragmatic approach to solve this budget crisis." },
  { word: "Meticulous", definition: "Showing great attention to detail; very careful and precise.", example: "The artist was meticulous in blending the colors." },
  { word: "Obscure", definition: "Not discovered or known about; uncertain.", example: "He found an obscure book hidden in the back of the library." },
  { word: "Profound", definition: "Very great or intense; having or showing great knowledge.", example: "The philosopher's words had a profound impact on her thinking." },
  { word: "Superfluous", definition: "Unnecessary, especially through being more than enough.", example: "The instructions were clear, making the extra diagrams superfluous." },
  { word: "Candid", definition: "Truthful and straightforward; frank.", example: "I appreciate your candid feedback on my presentation." },
  { word: "Aesthetic", definition: "Concerned with beauty or the appreciation of beauty.", example: "The new website has a highly modern and pleasing aesthetic." },
  { word: "Melancholy", definition: "A feeling of pensive sadness, typically with no obvious cause.", example: "The rainy weather brought on a sense of melancholy." },
  { word: "Nostalgia", definition: "A sentimental longing or wistful affection for the past.", example: "Hearing that old song filled him with nostalgia." },
  { word: "Paradox", definition: "A seemingly absurd or self-contradictory statement that may prove to be true.", example: "It's a paradox that sometimes less is more." },
  { word: "Stoic", definition: "Enduring pain or hardship without showing feelings or complaining.", example: "She remained stoic despite the harsh criticism." },
  { word: "Zealous", definition: "Showing great energy or enthusiasm in pursuit of a cause or objective.", example: "The zealous fan cheered the loudest at the concert." },
  { word: "Audacious", definition: "Showing a willingness to take surprisingly bold risks.", example: "It was an audacious plan to climb the mountain without ropes." },
  { word: "Lucid", definition: "Expressed clearly; easy to understand.", example: "The professor gave a lucid explanation of quantum physics." },
  { word: "Resonate", definition: "Produce or be filled with a deep, full, reverberating sound, or evoke a feeling.", example: "The movie's message about family will resonate with many viewers." },
  { word: "Lethargic", definition: "Affected by lethargy; sluggish and apathetic.", example: "After the huge meal, I felt completely lethargic." },
  { word: "Clandestine", definition: "Kept secret or done secretively, especially because illicit.", example: "The spies held a clandestine meeting in the alleyway." },
  { word: "Euphoria", definition: "A feeling or state of intense excitement and happiness.", example: "Winning the championship brought a wave of euphoria." },
  { word: "Vindicate", definition: "Clear someone of blame or suspicion.", example: "The DNA evidence will finally vindicate the wrongly accused man." },
  { word: "Frivolous", definition: "Not having any serious purpose or value.", example: "They spent their money on frivolous purchases instead of saving." },
];
